@startuml
'https://plantuml.com/sequence-diagram

'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response

'actor user #red
'boundary 边界 #blue
'control 控制 #green
'entity 实体  #pink
'database 数据库 #yellow

title web应用请求响应时序图

autonumber
activate 浏览器
浏览器 ->Nginx:获取静态资源html、css、js等
activate Nginx
Nginx ->Nginx:判断是静态资源
Nginx-->浏览器:返回静态页面
浏览器 ->浏览器 :渲染页面
浏览器 ->浏览器 :输入账号密码
浏览器 ->Nginx:登录

note left:(ajax请求调\n用后端API)
Nginx ->Nginx:非静态资源
Nginx -> TomcatSever:请求连接，建立session\n会话,创建sessionID

activate TomcatSever
TomcatSever-> UserController
activate UserController
UserController->业务处理:将参数传递给\n业务层（map）

activate 业务处理
业务处理 -> 业务处理:校验账号和密码
业务处理 -->UserController:返回验证结果
deactivate 业务处理

UserController --> TomcatSever:验证通过，将用户信\n息存放session域中（\n未通过返回错误信息）
deactivate UserController

TomcatSever-->Nginx:返回请求结果与\nsessionID
deactivate TomcatSever

Nginx -->浏览器
deactivate Nginx
浏览器 -> 浏览器:跳转页面，渲染视图\n存放sessionID

'
autonumber
浏览器 -> Nginx:查询（携带sessionID）
activate Nginx
Nginx ->Nginx:非静态资源
Nginx -> TomcatSever:请求连接，查询sessionID\n，返回session对象
activate TomcatSever
TomcatSever -> UserController
activate UserController
UserController -> 业务处理:将参数传递给\n业务层（map）
activate 业务处理
业务处理 ->业务处理:执行查询操作
UserController <-- 业务处理:返回查询结果
deactivate 业务处理
TomcatSever <-- UserController:统一数据格式\n返回json

deactivate UserController
Nginx <-- TomcatSever:返回json

deactivate TomcatSever

浏览器 <--Nginx
note left:获取数据,ajax\n异步更新页面
deactivate Nginx
浏览器->浏览器:解析HTML,渲染页面

@enduml


