@startuml
'https://plantuml.com/sequence-diagram

'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response

'actor user #red
'boundary 边界 #blue
'control 控制 #green
'entity 实体  #pink
'database 数据库 #yellow

title web应用请求响应时序图

autonumber
activate 浏览器
浏览器 ->Nginx:获取静态页面（html、css、js等）
activate Nginx
Nginx ->Nginx:匹配location
Nginx-->浏览器:返回静态页面
note right:Nginx正则匹配、\n动静分离
浏览器<-->Nginx:渲染页面
浏览器 ->浏览器 :输入账号密码
浏览器 ->Nginx:登录

note left:ajax请求调\n用后端API
Nginx ->Nginx:匹配location
Nginx -> TomcatSever:请求服务器连接

activate TomcatSever
TomcatSever-> 后端:调用后端API
activate 后端


后端 --> TomcatSever:返回结果与加密token
deactivate 后端

TomcatSever-->Nginx:
deactivate TomcatSever

Nginx -->浏览器:返回请求结果，保存token（cookie)
deactivate Nginx
浏览器 -> Nginx:请求跳转页面
activate Nginx
Nginx ->Nginx:匹配location

浏览器<-- Nginx:返回页面
浏览器<-->Nginx:渲染页面
deactivate Nginx

autonumber
浏览器 -> Nginx:查询（携带token）
activate Nginx
Nginx ->Nginx:匹配location
Nginx -> TomcatSever:请求连接服务器
activate TomcatSever
TomcatSever -> 后端:解密token，调用后端API
activate 后端

TomcatSever <-- 后端:返回请求结果

deactivate 后端
Nginx <-- TomcatSever:

deactivate TomcatSever

浏览器 <--Nginx
note left:获取数据,ajax\n异步更新页面
浏览器<-->Nginx:解析HTML,渲染页面
deactivate Nginx
@enduml


